- hosts: all
  become: yes
  vars:
    # TODO FOR DEVELOPERS: change dockerhub_username as appropriate
    dockerhub_username: "wmarcoyu"
    # TODO FOR USERS: set the installation path on target hosts
    install_path: "/home/wmarcoyu/pssid-gui2-pull-deploy"
    # (OPTIONAL) TODO FOR USERS: change application root directory
    pssid_gui_root_dir: "/usr/local/pssid_gui"
  tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Set up the Docker stable repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Ensure Docker is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Install Ansible
      apt:
        name: ansible
        state: present

    - name: Create the install directory
      file:
        path: "{{ install_path }}"
        state: directory

    - name: Rsync docker-compose.yml.j2 to the install directory
      synchronize:
        src: "{{ playbook_dir }}/docker-compose.yml.j2"
        dest: "{{ install_path }}/docker-compose.yml.j2"
        recursive: no

    - name: Generate docker-compose.yml from template
      template:
        src: "{{ install_path }}/docker-compose.yml.j2"
        dest: "{{ install_path }}/docker-compose.yml"

    - name: Pull Docker images
      command: docker-compose pull
      args:
        chdir: "{{ install_path }}"

    - name: Run Docker containers
      command: docker-compose up -d
      args:
        chdir: "{{ install_path }}"
